name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome, thank you for opening an issue. This is a first step in contributing to this repo"
        pr-message: "Thank you for creating a PR, the maintainer will review it and get back to you!!"
