name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    if: github.repository == 'akebu6/Kotlin-Notes 
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening an issue, the maintainer will have a look at it and get back to you as soon as possible. In the meantime you can look at the open issues and see if you would like to take up any😊'
        pr-message: 'Thanks so much for your contribution, really appreciated! We will have a look and merge it if everything checks out!'
